language: node_js
node_js: "16"

addons:
  sonarcloud:
    organization: "gu1lhem_soundbond" # the key of the org you chose at step #3
    token:
      secure: ${{ secrets.SONAR_TOKEN }} 
      
branches:
    only:
        - develop
        - main
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: develop
    tags: true
before_script:
    - cd client
    - yarn install
    - cd ../server
    - npm install nodemon	
    - sonar-scanner
cache:
    directories:
        - client/node_modules
        - server/node_modules
        - '$HOME/.sonar/cache'
script:
    - cd ../client
    - npm run build
    - cd ../server
    - npm run
notifications:
    slack: teamsoundbond:t070C9oXt6APmAQ5qrDegxrPcde1bdfe1aed03b66990b290e9b0783789849db6
