language: node_js
node_js: "16"
branches:
  only:
    - develop
    - main
addons:
  sonarcloud:
    organization: "soundbond" 
    token:
      secure: "sOV1l54EaUmGWZ4zMJ2ZwfNZF0h/Pu5shlDOP14NsXfrGpGWUHTLpRcelyKm7v7lR03MpIISWIiePByschodBcJw1MwBLbs/uZPWG1N97qstxMqFo7CEgjvCm5H2JlICBDev4KrfJC+gR1OH0c94YyHswNuBc4sCGQmB2PPK9rOzFu80j77+xnYuJ5afqKlWE2qdYW7lQo9TCNgNVUlYI6UXP0FvHJN8snWdgh0+3QZTU7lCoretpI826hiQVnb6Klbybync5M4g2y1ngFA8OyMMnrUmrRWzl0/HThNXXBkY++8E6jDaftWc9Y4InUGRNIRdN7SAZ2R3ooDKHVPb28ac7q2oPw1oO6skHuG7mAMYbFBz47lsYv5k3gOy+Md6A6Vnfw6/X137LXP0OX6C0F0E+of/vtZ4PmY+sjqtDaDk2IcOqabPGJDFpLv3Ee01dJR7pcM6b9ra4qMgxHjjxoRKeuaq15k+KwOvq6vjk4iVjoeUesc/clOqNWmGgnY3bAlxse0nXxKQu8C6tlPv8P+1RBlo3FVSvN4P+wRxgIvfs6xZq7IsylhVnwgpxZyJGR1vS5A2CnTXPhfyoAw4XKRE9TM7ziIpNLEF+0g6nh0omaYp3EQC6oyWixethukuqKsKpPTmxtpkrghuwCEST5+aqMVXVZCT9Ccvk2KotF0="
before_deploy:
  - export VERSION=$(node -p -e "require('./package.json').version")
  - export DOCDIR="docs/asciidoc"
  - export DOCFILE="sb"
  - mv "${DOCDIR}/sb.pdf" "${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - export DOCUMENTATION="${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - echo documentation is ${DOCUMENTATION}
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - ${DOCUMENTATION}
  on:
    branch: develop
    tags: true
after_deploy:
  - rm ${DOCUMENTATION}
  - rm docs/asciidoc/sb.html
before_script:
  - npm ci
  - cd client
  - yarn install
  - cd ../server
  - npm ci 
cache:
  directories:
    - client/node_modules
    - server/node_modules
script:
  - cd ..
  -  npm run asciidoc
  - cd ../client
  - npm run build
  - cd ../server
  - npm run
  - npm test
  - cd ..
  - sonar-scanner
notifications:
  slack: teamsoundbond:t070C9oXt6APmAQ5qrDegxrPcde1bdfe1aed03b66990b290e9b0783789849db6
