language: node_js
node_js: "16"
branches:
    only:
        - develop
        - main
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: develop
    tags: true
before_script:
    - cd client
    - npm install react-scripts
    - npm ci
    - cd ../server
    - npm ci			
cache:
    directories:
        - client/node_modules
        - server/node_modules
script:
    - npm test
    - npm run build
    - cd ../server
    - nodemon start
notifications:
    slack: teamsoundbond:t070C9oXt6APmAQ5qrDegxrPcde1bdfe1aed03b66990b290e9b0783789849db6
