language: node_js
node_js: "16"
branches:
  only:
    - develop
    - main
addons:
  sonarcloud:
    organization: "soundbond"
    token: ${SONAR_TOKEN}

before_deploy:
  - export VERSION=$(node -p -e "require('./package.json').version")
  - export DOCDIR="docs/asciidoc"
  - export DOCFILE="sb"
  - mv "${DOCDIR}/sb.pdf" "${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - export DOCUMENTATION="${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - echo documentation is ${DOCUMENTATION}
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - ${DOCUMENTATION}
  on:
    branch: develop
    tags: true
after_deploy:
  - rm ${DOCUMENTATION}
  - rm docs/asciidoc/sb.html
before_script:
  - npm ci
  - cd client
  - yarn install
  - cd ../server
  - npm ci
cache:
  directories:
    - client/node_modules
    - server/node_modules
script:
  - cd ..
  - npm run asciidoc
  - cd client
  - npm run build
  - cd ../server
  - npm run
  - npm run coverage
  - cd ..
  - sonar-scanner
notifications:
  slack: teamsoundbond:t070C9oXt6APmAQ5qrDegxrPcde1bdfe1aed03b66990b290e9b0783789849db6
