language: node_js
node_js: "16"
install:
    - npm install
    - npm install yarn
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: develop
    tags: true

cache:
  directories:
    - node_modules
script:
  - npm test
  - yarn build
