language: node_js
node_js: "16"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: develop
    tags: true

cache:
  directories:
    - client/node_modules
script:
  - npm test
  - cd client
  - npm run build
