# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy server to Azure Web App

on:
  push:
    branches:
      - main
  #    tags:
  #      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: "Production"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x" # was 14.x

      - name: npm install, build, and test
        run: |
          cd server
          yarn install

      - name: Writing .env config file for Production (/server)
        run: |
          cd server
          echo -e "DATABASE = "${{ secrets.DB_NAME }}"\nUSERNAME = "${{ secrets.DB_USERNAME }}"\nPASSWORD = "${{ secrets.DB_PASSWORD }}"\nHOST = "${{ secrets.DB_HOST }}"\nPORT = "${{ secrets.DB_PORT }}"\nAZURE_CONTAINER_NAME = ${{ secrets.AZURE_CONTAINER_NAME }}\nAZURE_CONNECTION_STRING = ${{ secrets.AZURE_CONNECTION_STRING }}\nTOKEN_SECRET = ${{ secrets.TOKEN_SECRET }}\nAZURE_STORAGE_TOKEN = ${{ secrets.AZURE_STORAGE_TOKEN }}\nAZURE_STORAGERESOURCENAME = ${{ secrets.AZURE_STORAGERESOURCENAME }}\n" >> .env

      - name: Zip artifact for deployment
        run: zip -q -r server-release.zip * .[^.]*
        working-directory: ./server/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./server/server-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -q server-release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "soundbond-node"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0B8845E416264582B1F6038D19BB96A0 }}
          package: .
