name: SonarCloud on main
on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
